Alpine Sprint Plone helm effort
plone/charts pull request #7
Opened 2024-04-11 13:54 UTC by xiru

All previous code from charts/plone is moded to plone6-volto-zeo without major changes.

Main changes are the following:
- renamed "plone" helm chart to "plone6-volto-zeo" (probably needs a refactory to become closer to other implementations)
- added new charts for plone using relstorage with postgresql, decouple frontend and backends, nginx and varnish
- change backends to StatefulSets, so we are able to use varnish directors and do proper load balancing (with backend failure graceful support)
- removed useless serviceaccounts (plone does not talk with k8s api, so we don't need that)
- turn ingress configs off by default. as a safety measure, ingress configs should be configured explicitly.
- add support for arbitrary injection of environmnet variables, enabling the usage of standard plone default env vars (e.g. turn on debug mode)
- add support for PodDisptionBugets on all objects with more than one replica.

Now this PR is read for code review :)

2024-04-11 14:03 UTC, xiru commented on charts/backend/templates/zodbpack.yaml
> +  name: zodbpack
This needs to be dynamic, so we allow more than one helm install in the same namespace.

2024-04-11 14:04 UTC, xiru commented on charts/backend/values.yaml
> +wsgiini: |-
@jensens this is the part we need to generate in a automated way, using cookiecutter (converting configuration files into k8s yamls)

2024-04-11 14:04 UTC, xiru commented on charts/plone/charts/zeoserver-0.1.0.tgz
I think these tgz files should not exist inside the repo.

2024-04-11 14:07 UTC, xiru commented on charts/plone6-volto-zeo/templates/backend-deployment.yaml
I'm not sure if we need to add an ingress for Plone backend API. We can use the k8s service instead and reduce overhead. Anyway, I did not removed this since I could not understand if there is any specific need for this ingress.

2024-04-11 14:07 UTC, xiru commented on charts/varnish/configmap.yaml
> +
We need to change this configmap to use varnish directors, using the backend instance names instead of a k8s service.

2024-04-11 14:12 UTC, xiru commented on charts/varnish/templates/ingress.yaml
I think we don't need an ingress for varnish. It is usually installed between nginx and plone FE nodes and should not be reachable beyond the network boundaries. Did not removed this file since I'm sure this is needed by someone.

2024-04-12 06:03 UTC, stevepiercy requested changes

2024-04-12 07:20 UTC, tschorr commented on backend/templates/NOTES.txt
> +1. Get the application URL by running these commands:
This is boilerplate coming with `helm create`. See the [Helm docs](https://helm.sh/docs/topics/charts/#chart-license-readme-and-notes) for what needs to go in this file.

2024-04-12 09:00 UTC, stevepiercy commented on backend/templates/NOTES.txt
> +1. Get the application URL by running these commands:
Thanks for the reference.

Is there any content from any of the NOTES.txt files that can be moved into a README.md? It looks like it is a template, so maybe not?

It would be nice to avoid copy-paste if these files ever need to be changed.

2024-04-12 12:30 UTC, tschorr commented on backend/templates/NOTES.txt
> +1. Get the application URL by running these commands:
Yes it's a template. For our use cases I'd say usage notes should go in NOTES.txt (in line with the helm docs) and also some specific hints on how to setup a Plone site if the database is empty (pods will crash and keep restarting when there is no site).

README.md should contain a description of the specific setup (e.g. classic/volto, db included/db external, varnish yes/no, ingress options).

2024-04-13 10:35 UTC, stevepiercy requested changes
Can the diagrams be exported as SVG instead of PNG? I would love to be able to read the text.

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +If you want to run Plone 6 on Kubernetes this is probably a good starting point.
I would say it is the _only_ starting point, but maybe that won't be true for long. 😁 

```suggestion
If you want to run Plone 6 on Kubernetes, this repository is a good starting point.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +* Add a helm repo and use the published charts - see the next section on how to do this
```suggestion
* Add a Helm repository, and use the published charts. See the next section on how to do that.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +* Clone/fork the repository to adapt the charts to your needs or create new charts
```suggestion
* Clone or fork the repository, and adapt the charts to your needs, or create new charts.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +available tags [here](https://quay.io/repository/helmpack/chart-testing?tab=tags).
```suggestion
[available tags](https://quay.io/repository/helmpack/chart-testing?tab=tags).
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +* [ct version](doc/ct_version.md)
Where are these files? None of these links work.

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +For a more extensive how-to guide, please see:
```suggestion
For a more extensive how-to guide, see [charts-repo-actions-demo](https://github.com/helm/charts-repo-actions-demo).
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +* [charts-repo-actions-demo](https://github.com/helm/charts-repo-actions-demo)
```suggestion
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +`ct` is a command-line application.
```suggestion
`ct` is a command line application.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +All command-line flags can also be set via environment variables or config file.
```suggestion
All command line flags can be set via environment variables or a configuration file.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +CLI flags, environment variables, and a config file can be mixed.
```suggestion
You can mix CLI flags, environment variables, and a configuration file when running `ct`.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +1. Config file
```suggestion
1. Configuration file
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +Note that linting requires config file for [yamllint](https://github.com/adrienverge/yamllint) and [yamale](https://github.com/23andMe/Yamale).
```suggestion
Note that linting requires a configuration file for [yamllint](https://github.com/adrienverge/yamllint) and [yamale](https://github.com/23andMe/Yamale).
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +If not specified, these files are search in the current directory, the `.ct` directory in current directory, `$HOME/.ct`, and `/etc/ct`, in that order.
```suggestion
If not specified, `ct` searches in the current directory, the `.ct` directory in the current directory, `$HOME/.ct`, and `/etc/ct`, in that order.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +Samples are provided in the [etc](etc) folder.
This should not be a link.

```suggestion
Samples are provided in the `etc` folder.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +The following example show various way of configuring the same thing:
```suggestion
The following examples show various way of configuring the same thing.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +    ct install --remote upstream --chart-dirs stable,incubator --build-id pr-42
Let's specify the syntax, so that GitHub does not guess incorrectly.

````suggestion
```shell
ct install --remote upstream --chart-dirs stable,incubator --build-id pr-42
```
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +If you have a chart in current directory and ct installed on the host then you can run:
```suggestion
If you have a chart in the current directory, and `ct` installed on the host, then you can run the following command.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +    ct install --chart-dirs . --charts .
````suggestion
```shell
ct install --chart-dirs . --charts .
```
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +With docker it works with:
```suggestion
With Docker, it works with:
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +    docker run -it --network host --workdir=/data --volume ~/.kube/config:/root/.kube/config:ro --volume $(pwd):/data quay.io/helmpack/chart-testing:v3.7.1 ct install --chart-dirs . --charts .
````suggestion
```shell
docker run -it --network host --workdir=/data --volume ~/.kube/config:/root/.kube/config:ro --volume $(pwd):/data quay.io/helmpack/chart-testing:v3.7.1 ct install --chart-dirs . --charts .
```
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +Notice that `workdir` param is important and must be the same as volume mounted.
```suggestion
Notice that the `workdir` parameter is important, and must have the same as the name of the mounted volume.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +    ct install
Replace above commands with the following.

````suggestion
```shell
export CT_REMOTE=upstream
export CT_CHART_DIRS=stable,incubator
export CT_BUILD_ID

ct install
```
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +#### Config Usage
```suggestion
#### Configuration usage
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +    ct install --config config.yaml
````suggestion
```shell
ct install --config config.yaml
```
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +`ct` supports any format [Viper](https://github.com/spf13/viper) can read, i. e. JSON, TOML, YAML, HCL, and Java properties files.
```suggestion
`ct` supports any format [Viper](https://github.com/spf13/viper) can read, including JSON, TOML, YAML, HCL, and Java properties files.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +Notice that if no config file is specified, then `ct.yaml` (or any of the supported formats) is loaded from the current directory, `$HOME/.ct`, or `/etc/ct`, in that order, if found.
```suggestion
Notice that if no configuration file is specified, then `ct.yaml` (or any of the supported formats) is loaded from the current directory, `$HOME/.ct`, or `/etc/ct`, in that order, if found.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +When adding chart-repos you can specify additional arguments for the `helm repo add` command using `helm-repo-extra-args` on a per-repo basis.
```suggestion
When adding chart repositories, you can specify additional arguments for the `helm repo add` command using `helm-repo-extra-args` on a per-repository basis.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +You can also specify OCI registries which will be added using the `helm registry login` command, they also support the `helm-repo-extra-args` for authentication.
```suggestion
You can also specify OCI registries which will be added using the `helm registry login` command.
They also support the `helm-repo-extra-args` for authentication.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +This could for example be used to authenticate a private chart repository.
```suggestion
The following example could be used to authenticate a private chart repository.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +    ct install --config config.yaml --helm-repo-extra-args "basic-auth=--username user --password secret"
````suggestion
```shell
ct install --config config.yaml --helm-repo-extra-args "basic-auth=--username user --password secret"
```
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +Note: on MacOS you will need `GNU Coreutils readlink`.
```suggestion
Note: on macOS, you will need GNU Coreutils readlink.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +```console
````suggestion
```shell
````

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +```console
```suggestion
```shell
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +```console
```suggestion
```shell
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +### Prepare Release
```suggestion
### Prepare release
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +### Create Release
```suggestion
### Create release
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +Versions must start with a lower-case `v`, e. g. `v3.7.1`.
```suggestion
Versions must start with a lower-case `v`, for example, `v3.7.1`.
```

2024-04-13 10:35 UTC, stevepiercy commented on README.md
> +This is because, while the [v2.0.0](https://github.com/helm/chart-testing/releases/tag/v2.0.0) release has parity with `v1`, it was refactored from a bash library to Go so there are minor syntax diff
```suggestion
This is because, while the [v2.0.0](https://github.com/helm/chart-testing/releases/tag/v2.0.0) release has parity with `v1`, it was refactored from a bash library to Go, so there are minor syntax differences.
```

2024-04-13 10:35 UTC, stevepiercy commented on plone6-volto-pg/README.md
> +# Install Plone 6 with RelStorage/PostgreSQL, Volto and optional Traefik IngressRoute
```suggestion
# Install Plone 6 with RelStorage/PostgreSQL, Volto, and optional Traefik IngressRoute
```

2024-04-13 10:35 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +The external database can be located inside or outside of your Kubernetes cluster (or the namespace you use to install this chart), it just has to be accessible.
```suggestion
The external database can be located inside or outside of your Kubernetes cluster, or the namespace you use to install this chart, as long as it is accessible.
```

2024-04-13 10:35 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +This Helm chart combines the postgresql installs a Plone backend to use as Plone 6 Classic and optional Ingress.
```suggestion
This Helm chart installs a Plone backend, Plone 6 Classic UI for the frontend, and an optional Ingress.
```

2024-04-13 10:35 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +### Ingress
Much empty, so sad 😢 .

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +# Deployment Scenarious with Kubernetes
```suggestion
# Deployment scenarious with Kubernetes
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +Other use-cases can build on top of these scenarios.
```suggestion
Other use cases can build on top of these scenarios.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +We identified different scenarios for deploying the Plone with Kubernetes.
```suggestion
We identified different scenarios for deploying Plone with Kubernetes.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +DRAFT/WIP
```suggestion
If you don't see your scenario in this document, we would welcome a pull request.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +The scenarious are written from simple to complex and are build on top of each other.
```suggestion
The scenarious are written from simple to complex and build on top of each other.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +It uses a databse, stores the blobs in the database and uses the Classic UI, which is provided by the `plone-backend` container only.
```suggestion
It uses a database, stores the blobs in the database, and uses Classic UI, which is provided by the `plone-backend` container.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +The image is used as-is, without any additional addons.
```suggestion
The image is used as-is, without any additional add-ons.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +The plone-backend pods are connecting to the PostgreSQL.
```suggestion
The `plone-backend` pods connect to the PostgreSQL pod.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +Volto is the default Plone 6 Frontend.
```suggestion
Volto is the default Plone 6 frontend.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +This scenario is the minimal default setup for a modern Plone 6 in Kubernetes with a routing-capable ingress controller.
```suggestion
This scenario is the minimal default setup for a modern Plone 6 site in Kubernetes with a routing-capable ingress controller.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +It provides the Plone Backend API server, which is run by the `plone-backend` image.
```suggestion
It provides the Plone backend API server, which is run by the `plone-backend` image.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +Both images are used as-is, without any additional addons.
```suggestion
Both images are used as-is, without any additional add-ons.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +Also, it needs an ingress with HTTP routing capabilities, e.g. a Traefik ingress controller.
```suggestion
Also, it needs an ingress with HTTP routing capabilities, such as a Traefik ingress controller.
```

2024-04-13 10:35 UTC, stevepiercy commented on SCENARIOS.md
> +The nginx will be configured to route the requests to the `plone-frontend` and `plone-backend` pods, dependent on the requests path.
```suggestion
The `nginx` pod will be configured to route the requests to the `plone-frontend` and `plone-backend` pods, depending on the requests path.
```

2024-04-13 11:37 UTC, xiru commented
> Can the diagrams be exported as SVG instead of PNG? I would love to be able to read the text.

yes, that's possible. I will do that change.

2024-04-15 07:18 UTC, tschorr approved these changes
I have tried to apply some of @stevepiercy s suggestions and I have restored the README.md and the LICENSE (they had been replaced from another repository).

Other than that, I'd like to see this merged even if there are still a couple of things to do. We can then address open issues in  subsequent pull requests.

2024-04-17 08:53 UTC, jensens commented
I am going to merge this if there are no further complaints within the next 24h.

2024-04-17 09:15 UTC, stevepiercy commented
@jensens please wait for me to review docs again. I don't want to lose all the suggestions in this PR and start all over. I've been super busy or sick at the Axolote Sprint.

2024-04-17 11:24 UTC, jensens commented
> @stevepiercy  ... super busy or sick at the Axolote Sprint.
Together this does not sound like a healthy combination. Get well soon!

2024-04-17 19:16 UTC, stevepiercy requested changes
I need to submit a review before I can commit my suggestions.

2024-04-17 19:16 UTC, stevepiercy commented on README.md
> +* As a library of subcharts that you can use to create your own composite charts
```suggestion
* Use as collection of subcharts from which you can create your own composite charts.
```

2024-04-17 19:16 UTC, stevepiercy commented on SCENARIOS.md
> +### Description
Avoid headings without content. In this case the description does not need a subheading, as it describes the parent heading.

```suggestion
```

2024-04-17 19:16 UTC, stevepiercy commented on SCENARIOS.md
> +### Description
```suggestion
```

2024-04-17 19:16 UTC, stevepiercy commented on SCENARIOS.md
> +### Description
```suggestion
```

2024-04-17 19:16 UTC, stevepiercy commented on SCENARIOS.md
> +Additional to scenario 2 this scenario needs a `nginx` pod.
```suggestion
Additional to scenario 2 this scenario needs an `nginx` pod.
```

2024-04-17 19:16 UTC, stevepiercy commented on plone6-classic-pg/README.md
> +### Ingress
We can merge without content for these headings, and if so, then create a new issue to capture the need for documentation.

2024-04-17 19:16 UTC, stevepiercy commented on plone6-volto-pg/README.md
> +### Ingress
We can merge without content for these headings, and if so, then create a new issue to capture the need for documentation.

2024-04-17 19:22 UTC, stevepiercy requested changes
One more batch of commits incoming.

2024-04-17 19:22 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +### Ingress
We can merge without content for these headings, and if so, then create a new issue to capture the need for documentation.

2024-04-17 19:22 UTC, stevepiercy commented on plone6-volto-pg-nginx-varnish/README.md
> +# Install Plone 6 with RelStorage/PostgreSQL, Volto and optional Traefik IngressRoute
```suggestion
# Install Plone 6 with RelStorage/PostgreSQL, Volto, and optional Traefik IngressRoute
```

2024-04-17 19:24 UTC, stevepiercy approved these changes
Docs are good to go, with the caveat that the empty sections either should be filled in or a new issue created if left blank when merged.

2024-04-18 13:11 UTC, merged